export const TEXT = {
  brand: 'Keywise',
  title: 'Поиск игровых ключей',
  game: 'Игра',
  gamePlaceholder: 'Elden Ring',
  region: 'Регион',
  steam: 'Steam',
  steamPlaceholder: 'URL профиля или SteamID64',
  search: 'Поиск',
  loading: 'Идёт поиск…',
  searchFailed: 'Не удалось выполнить поиск',
  empty: 'Ничего не найдено',
  bestOffer: 'Лучшее предложение',
  wishlist: 'Вишлист Steam',
  wishlistEmpty: 'Вишлист пуст или недоступен',
  wishlistSelected: 'Искомая игра в списке',
  wishlistMissing: 'Искомой игры нет в списке',
  wishlistOpen: 'Steam',
  wishlistExpand: 'Показать вишлист',
  wishlistCollapse: 'Скрыть вишлист',
  selectedBadge: 'Искомая',
  open: 'Открыть',
  source: 'Источник',
  shop: 'Магазин',
  price: 'Цена',
  link: 'Ссылка',
} as const;
